"""Version-matched, structured EnergyPlus model preparation through epJSON."""

from __future__ import annotations

import copy
import csv
import hashlib
import json
import math
import shutil
import subprocess
import tempfile
from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from ecoloop.config import repository_root
from ecoloop.energyplus.discovery import EnergyPlusInstallation, require_energyplus
from ecoloop.exceptions import EnergyPlusIntegrationError

_OUTPUT_VARIABLES: tuple[tuple[str, str], ...] = (
    ("Zone Mean Air Temperature", "*"),
    ("Zone Operative Temperature", "*"),
    ("Zone Air Relative Humidity", "*"),
    ("Zone People Occupant Count", "*"),
    ("Site Outdoor Air Drybulb Temperature", "Environment"),
    ("Zone Thermostat Heating Setpoint Temperature", "*"),
    ("Zone Thermostat Cooling Setpoint Temperature", "*"),
    ("Facility Total Electricity Demand Rate", "Whole Building"),
)
_OUTPUT_METERS = ("Electricity:Facility", "ElectricityNet:Facility", "Electricity:HVAC")
_FANGER_SCHEDULE_VALUES: dict[str, float] = {
    "EcoLoop Work Efficiency": 0.0,
    "EcoLoop Summer Office Clothing": 0.5,
    "EcoLoop Air Velocity": 0.1,
}
_FANGER_SCHEDULE_TYPES: dict[str, str] = {
    "EcoLoop Work Efficiency": "EcoLoop Work Efficiency Limits",
    "EcoLoop Summer Office Clothing": "EcoLoop Clothing Insulation Limits",
    "EcoLoop Air Velocity": "EcoLoop Air Velocity Limits",
}
_FANGER_TYPE_LIMITS: dict[str, dict[str, Any]] = {
    "EcoLoop Work Efficiency Limits": {
        "lower_limit_value": 0.0,
        "upper_limit_value": 1.0,
        "numeric_type": "Continuous",
        "unit_type": "Dimensionless",
    },
    "EcoLoop Clothing Insulation Limits": {
        "lower_limit_value": 0.0,
        "upper_limit_value": 2.0,
        "numeric_type": "Continuous",
        "unit_type": "Dimensionless",
    },
    "EcoLoop Air Velocity Limits": {
        "lower_limit_value": 0.0,
        "upper_limit_value": 2.0,
        "numeric_type": "Continuous",
        "unit_type": "Velocity",
    },
}
_THERMOSTAT_FIELDS: dict[str, tuple[str | None, str | None]] = {
    "ThermostatSetpoint:DualSetpoint": (
        "heating_setpoint_temperature_schedule_name",
        "cooling_setpoint_temperature_schedule_name",
    ),
    "ThermostatSetpoint:SingleHeating": ("setpoint_temperature_schedule_name", None),
    "ThermostatSetpoint:SingleCooling": (None, "setpoint_temperature_schedule_name"),
}


@dataclass(frozen=True, slots=True)
class ModelProvenance:
    """Recorded origin and selection rationale for the copied example model."""

    source_path: Path
    source_name: str
    energyplus_version: str
    energyplus_home: Path
    license_path: Path | None
    selection_reasons: tuple[str, ...]


@dataclass(frozen=True, slots=True)
class ModelArtifacts:
    """Paths generated by model preparation."""

    source_model: Path
    baseline_model: Path
    agent_ready_model: Path
    agent_replay_model: Path
    action_schedule: Path
    actuator_map: Path
    provenance: Path
    preparation_manifest: Path


@dataclass(frozen=True, slots=True)
class CandidateExample:
    """One scored official example model."""

    path: Path
    score: int
    reasons: tuple[str, ...]


class PeriodProtocol(Protocol):
    """Calendar attributes required by model preparation."""

    start_month: int
    start_day: int
    end_month: int
    end_day: int


class SchemaNavigator:
    """Look up object and field definitions in the installed EnergyPlus schema."""

    def __init__(self, schema: Mapping[str, Any]) -> None:
        self._schema = schema

    def _resolve(self, value: Mapping[str, Any]) -> Mapping[str, Any]:
        reference = value.get("$ref")
        if not isinstance(reference, str):
            return value
        if not reference.startswith("#/"):
            raise EnergyPlusIntegrationError(f"Unsupported external schema reference: {reference}")
        current: Any = self._schema
        for part in reference[2:].split("/"):
            current = current[part.replace("~1", "/").replace("~0", "~")]
        if not isinstance(current, Mapping):
            raise EnergyPlusIntegrationError(f"Schema reference is not an object: {reference}")
        return self._resolve(current)

    def object_schema(self, object_type: str) -> Mapping[str, Any]:
        """Return the schema for one epJSON object instance."""

        properties = self._schema.get("properties")
        if not isinstance(properties, Mapping) or object_type not in properties:
            raise EnergyPlusIntegrationError(
                f"EnergyPlus 26.1 schema does not define object type {object_type!r}."
            )
        container = properties[object_type]
        if not isinstance(container, Mapping):
            raise EnergyPlusIntegrationError(f"Invalid schema container for {object_type!r}.")
        container = self._resolve(container)
        patterns = container.get("patternProperties")
        if isinstance(patterns, Mapping) and patterns:
            pattern_value = next(iter(patterns.values()))
            if isinstance(pattern_value, Mapping):
                return self._resolve(pattern_value)
        additional = container.get("additionalProperties")
        if isinstance(additional, Mapping):
            return self._resolve(additional)
        raise EnergyPlusIntegrationError(
            f"Could not locate instance fields for schema object {object_type!r}."
        )

    def has_object(self, object_type: str) -> bool:
        """Return whether an object type exists in the installed schema."""

        properties = self._schema.get("properties")
        return isinstance(properties, Mapping) and object_type in properties

    def field_names(self, object_type: str) -> frozenset[str]:
        """Return valid field names for an object type."""

        properties = self.object_schema(object_type).get("properties")
        if not isinstance(properties, Mapping):
            return frozenset()
        return frozenset(str(item) for item in properties)

    def require_fields(self, object_type: str, fields: Iterable[str]) -> None:
        """Require fields before modifying a model, preventing guessed field writes."""

        valid = self.field_names(object_type)
        missing = sorted(set(fields) - valid)
        if missing:
            raise EnergyPlusIntegrationError(
                f"EnergyPlus 26.1 schema object {object_type!r} lacks fields: {', '.join(missing)}."
            )

    def validate_instance_fields(self, object_type: str, instance: Mapping[str, Any]) -> None:
        """Reject fields not advertised by the version-matched schema."""

        self.require_fields(object_type, instance.keys())


def load_epjson_schema(path: Path) -> tuple[dict[str, Any], SchemaNavigator]:
    """Load the installed EnergyPlus epJSON schema."""

    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise EnergyPlusIntegrationError(f"Could not load EnergyPlus schema {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise EnergyPlusIntegrationError(f"EnergyPlus schema {path} is not a JSON object.")
    return value, SchemaNavigator(value)


def _read_model_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace").casefold()


def score_example_model(path: Path) -> CandidateExample:
    """Score an official example for a fast multi-zone supervisory-control demo."""

    name = path.name.casefold()
    text = _read_model_text(path)
    score = 0
    reasons: list[str] = []
    if "smalloffice" in name:
        score += 40
        reasons.append("small-office example")
    if "5zone" in name or "fivezone" in name:
        score += 35
        reasons.append("five-zone example")
    if text.count("zone,") >= 3:
        score += 20
        reasons.append("multiple zones")
    if "people," in text:
        score += 12
        reasons.append("People objects")
    if "zonectrl:thermostat" in text or "zonecontrol:thermostat" in text:
        score += 12
        reasons.append("zone thermostats")
    if "coil:heating:electric" in text:
        score += 15
        reasons.append("electric heating")
    if "coil:cooling:dx" in text:
        score += 12
        reasons.append("DX cooling")
    if "heatpump" in name or "heat pump" in text:
        score += 15
        reasons.append("heat-pump equipment")
    if "naturalgas" in text or "natural gas" in text:
        score -= 8
        reasons.append("contains non-electric fuel")
    if path.stat().st_size > 2_000_000:
        score -= 20
        reasons.append("large model")
    if "advanced" in name or "benchmark" in name:
        score -= 12
        reasons.append("complex example")
    return CandidateExample(path.resolve(), score, tuple(reasons))


def select_official_example(installation: EnergyPlusInstallation) -> CandidateExample:
    """Select the highest-scoring official version-matched example model."""

    examples = installation.example_files
    if examples is None or not examples.is_dir():
        raise EnergyPlusIntegrationError(
            f"EnergyPlus ExampleFiles were not found below {installation.home}. "
            "Reinstall the complete 26.1.0 distribution or configure an explicit source model."
        )
    candidates = [score_example_model(path) for path in examples.rglob("*.idf") if path.is_file()]
    eligible = [
        item
        for item in candidates
        if "multiple zones" in item.reasons
        and "People objects" in item.reasons
        and "zone thermostats" in item.reasons
    ]
    if not eligible:
        raise EnergyPlusIntegrationError(
            f"No official example under {examples} met the multi-zone/People/thermostat criteria."
        )
    return sorted(eligible, key=lambda item: (-item.score, item.path.name.casefold()))[0]


def _conversion_output(work: Path, stem: str, target_format: str) -> Path | None:
    suffixes = {
        "epJSON": (".epJSON", ".epjson"),
        "idf": (".idf", ".IDF"),
    }[target_format]
    for suffix in suffixes:
        candidate = work / f"{stem}{suffix}"
        if candidate.is_file():
            return candidate
    for candidate in work.iterdir():
        if (
            candidate.is_file()
            and candidate.stem.casefold() == stem.casefold()
            and candidate.suffix.casefold() in {item.casefold() for item in suffixes}
        ):
            return candidate
    return None


def convert_input_format(
    installation: EnergyPlusInstallation,
    source: Path,
    target_format: str,
    destination: Path,
) -> Path:
    """Convert IDF/epJSON using the installed official ConvertInputFormat tool."""

    if target_format not in {"epJSON", "idf"}:
        raise ValueError(f"Unsupported EnergyPlus conversion format: {target_format}")
    tool = installation.convert_input_format
    if tool is None:
        raise EnergyPlusIntegrationError(
            f"ConvertInputFormat was not found below {installation.home}."
        )
    if not source.is_file():
        raise EnergyPlusIntegrationError(f"Model source does not exist: {source}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="ecoloop-convert-") as temporary:
        work = Path(temporary)
        local_source = work / source.name
        shutil.copy2(source, local_source)
        command = [str(tool), "--format", target_format, str(local_source)]
        try:
            completed = subprocess.run(  # noqa: S603 - official tool path is discovered
                command,
                cwd=work,
                capture_output=True,
                check=False,
                text=True,
                timeout=120,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise EnergyPlusIntegrationError(
                f"ConvertInputFormat could not process {source}: {exc}"
            ) from exc
        output = _conversion_output(work, local_source.stem, target_format)
        if completed.returncode != 0 or output is None:
            diagnostic = "\n".join(
                value.strip() for value in (completed.stdout, completed.stderr) if value.strip()
            )
            raise EnergyPlusIntegrationError(
                f"ConvertInputFormat failed for {source} (exit {completed.returncode}). "
                f"Output: {diagnostic or 'no diagnostic output'}"
            )
        shutil.copy2(output, destination)
    return destination


def _instances(model: dict[str, Any], object_type: str) -> dict[str, dict[str, Any]]:
    value = model.setdefault(object_type, {})
    if not isinstance(value, dict):
        raise EnergyPlusIntegrationError(f"epJSON object {object_type!r} is not a mapping.")
    for key, instance in value.items():
        if not isinstance(instance, dict):
            raise EnergyPlusIntegrationError(
                f"epJSON object {object_type!r}/{key!r} is not a mapping."
            )
    return value


def _temperature_type_limit(
    model: dict[str, Any],
    schema: SchemaNavigator,
) -> str:
    object_type = "ScheduleTypeLimits"
    existing = _instances(model, object_type)
    valid_fields = schema.field_names(object_type)
    for name, instance_fields in existing.items():
        unit = instance_fields.get("unit_type")
        if isinstance(unit, str) and unit.casefold() == "temperature":
            return name
    fields: dict[str, Any] = {}
    if "unit_type" in valid_fields:
        fields["unit_type"] = "Temperature"
    if "numeric_type" in valid_fields:
        fields["numeric_type"] = "Continuous"
    schema.validate_instance_fields(object_type, fields)
    existing["EcoLoop Temperature"] = fields
    return "EcoLoop Temperature"


def _baseline_schedule_data(occupied: float, unoccupied: float) -> list[dict[str, str | float]]:
    return [
        {"field": "Through: 12/31"},
        {"field": "For: Weekdays SummerDesignDay WinterDesignDay CustomDay1 CustomDay2"},
        {"field": "Until: 08:00"},
        {"field": unoccupied},
        {"field": "Until: 18:00"},
        {"field": occupied},
        {"field": "Until: 24:00"},
        {"field": unoccupied},
        {"field": "For: Weekends Holiday"},
        {"field": "Until: 24:00"},
        {"field": unoccupied},
    ]


def _install_baseline_schedules(
    model: dict[str, Any],
    schema: SchemaNavigator,
    *,
    controlled: bool,
) -> tuple[str, str, str, str, int]:
    schedule_type = "Schedule:Compact"
    schema.require_fields(schedule_type, ("schedule_type_limits_name", "data"))
    temperature_limit = _temperature_type_limit(model, schema)
    schedules = _instances(model, schedule_type)

    reference_heating = "EcoLoop Reference Heating Setpoint"
    reference_cooling = "EcoLoop Reference Cooling Setpoint"
    actuated_heating = "EcoLoop Actuated Heating Setpoint"
    actuated_cooling = "EcoLoop Actuated Cooling Setpoint"
    heating = {
        "schedule_type_limits_name": temperature_limit,
        "data": _baseline_schedule_data(20.0, 18.0),
    }
    cooling = {
        "schedule_type_limits_name": temperature_limit,
        "data": _baseline_schedule_data(24.0, 28.0),
    }
    schema.validate_instance_fields(schedule_type, heating)
    schema.validate_instance_fields(schedule_type, cooling)
    schedules[reference_heating] = copy.deepcopy(heating)
    schedules[reference_cooling] = copy.deepcopy(cooling)
    schedules[actuated_heating] = copy.deepcopy(heating)
    schedules[actuated_cooling] = copy.deepcopy(cooling)

    heating_target = actuated_heating if controlled else reference_heating
    cooling_target = actuated_cooling if controlled else reference_cooling
    patched = 0
    for object_type, (heating_field, cooling_field) in _THERMOSTAT_FIELDS.items():
        if not schema.has_object(object_type):
            continue
        fields = tuple(field for field in (heating_field, cooling_field) if field)
        schema.require_fields(object_type, fields)
        for thermostat in _instances(model, object_type).values():
            if heating_field:
                thermostat[heating_field] = heating_target
            if cooling_field:
                thermostat[cooling_field] = cooling_target
            patched += 1
    if patched == 0:
        raise EnergyPlusIntegrationError(
            "The selected model has no supported thermostat setpoint object. "
            "No schedule fields were guessed or rewritten."
        )
    return (
        reference_heating,
        reference_cooling,
        actuated_heating,
        actuated_cooling,
        patched,
    )


def _add_output_variable(
    model: dict[str, Any],
    schema: SchemaNavigator,
    variable_name: str,
    key: str,
    *,
    label: str | None = None,
) -> None:
    object_type = "Output:Variable"
    fields = {
        "key_value": key,
        "variable_name": variable_name,
        "reporting_frequency": "Timestep",
    }
    schema.validate_instance_fields(object_type, fields)
    output = _instances(model, object_type)
    instance_name = label or f"EcoLoop {variable_name} {key}"
    output[instance_name] = fields


def _add_outputs(
    model: dict[str, Any],
    schema: SchemaNavigator,
    reference_schedules: tuple[str, str],
    actuated_schedules: tuple[str, str],
    *,
    include_fanger: bool,
) -> None:
    for variable_name, key in _OUTPUT_VARIABLES:
        _add_output_variable(model, schema, variable_name, key)

    contaminant = model.get("ZoneAirContaminantBalance")
    if isinstance(contaminant, Mapping) and contaminant:
        _add_output_variable(model, schema, "Zone Air CO2 Concentration", "*")
    if include_fanger:
        _add_output_variable(
            model,
            schema,
            "Zone Thermal Comfort Fanger Model PMV",
            "*",
        )
        _add_output_variable(
            model,
            schema,
            "Zone Thermal Comfort Fanger Model PPD",
            "*",
        )

    for schedule_name in (*reference_schedules, *actuated_schedules):
        _add_output_variable(
            model,
            schema,
            "Schedule Value",
            schedule_name,
            label=f"EcoLoop Schedule Value {schedule_name}",
        )

    meter_type = "Output:Meter"
    schema.require_fields(meter_type, ("key_name", "reporting_frequency"))
    meters = _instances(model, meter_type)
    for meter_name in _OUTPUT_METERS:
        fields = {"key_name": meter_name, "reporting_frequency": "Timestep"}
        schema.validate_instance_fields(meter_type, fields)
        meters[f"EcoLoop {meter_name}"] = fields

    sqlite_type = "Output:SQLite"
    if schema.has_object(sqlite_type):
        valid = schema.field_names(sqlite_type)
        field = "option_type" if "option_type" in valid else None
        if field:
            sqlite = _instances(model, sqlite_type)
            sqlite["EcoLoop SQLite"] = {field: "SimpleAndTabular"}


def _enable_fanger_when_supported(
    model: dict[str, Any],
    schema: SchemaNavigator,
) -> tuple[int, dict[str, str]]:
    object_type = "People"
    if not schema.has_object(object_type):
        return 0, {}
    valid = schema.field_names(object_type)
    comfort_fields = [
        field
        for field in (
            "thermal_comfort_model_1_type",
            "thermal_comfort_model_2_type",
            "thermal_comfort_model_3_type",
            "thermal_comfort_model_4_type",
            "thermal_comfort_model_5_type",
            "thermal_comfort_model_6_type",
            "thermal_comfort_model_7_type",
        )
        if field in valid
    ]
    if not comfort_fields:
        return 0, {}
    prerequisite_fields = (
        "activity_level_schedule_name",
        "clothing_insulation_schedule_name",
        "air_velocity_schedule_name",
        "work_efficiency_schedule_name",
        "clothing_insulation_calculation_method",
        "mean_radiant_temperature_calculation_type",
    )
    schema.require_fields(object_type, prerequisite_fields)
    schema.require_fields(
        "Schedule:Constant",
        ("schedule_type_limits_name", "hourly_value"),
    )
    type_limits = _instances(model, "ScheduleTypeLimits")
    for type_name, type_fields in _FANGER_TYPE_LIMITS.items():
        schema.validate_instance_fields("ScheduleTypeLimits", type_fields)
        existing_type = type_limits.get(type_name)
        if existing_type is not None and existing_type != type_fields:
            raise EnergyPlusIntegrationError(
                f"Cannot install Fanger schedule limits {type_name!r}: "
                "the model already defines that name with different fields."
            )
        type_limits[type_name] = copy.deepcopy(type_fields)

    constant_schedules = _instances(model, "Schedule:Constant")
    for schedule_name, value in _FANGER_SCHEDULE_VALUES.items():
        schedule = {
            "schedule_type_limits_name": _FANGER_SCHEDULE_TYPES[schedule_name],
            "hourly_value": value,
        }
        schema.validate_instance_fields("Schedule:Constant", schedule)
        existing = constant_schedules.get(schedule_name)
        if existing is not None and existing != schedule:
            raise EnergyPlusIntegrationError(
                f"Cannot install Fanger prerequisite schedule {schedule_name!r}: "
                "the model already defines that name with different fields."
            )
        constant_schedules[schedule_name] = schedule

    people = _instances(model, object_type)
    enabled = 0
    people_zone_map: dict[str, str] = {}
    for people_name, fields in people.items():
        activity = fields.get("activity_level_schedule_name")
        if not isinstance(activity, str) or not activity:
            continue
        zone_name = fields.get("zone_or_zonelist_or_space_or_spacelist_name")
        if isinstance(zone_name, str) and zone_name:
            people_zone_map[people_name] = zone_name
        fields.setdefault(
            "work_efficiency_schedule_name",
            "EcoLoop Work Efficiency",
        )
        if not fields.get("clothing_insulation_schedule_name"):
            fields["clothing_insulation_schedule_name"] = "EcoLoop Summer Office Clothing"
            fields["clothing_insulation_calculation_method"] = "ClothingInsulationSchedule"
        else:
            fields.setdefault(
                "clothing_insulation_calculation_method",
                "ClothingInsulationSchedule",
            )
        fields.setdefault("air_velocity_schedule_name", "EcoLoop Air Velocity")
        fields.setdefault(
            "mean_radiant_temperature_calculation_type",
            "EnclosureAveraged",
        )
        if not all(
            isinstance(fields.get(item), str) and fields[item] for item in prerequisite_fields
        ):
            continue
        if not any(
            isinstance(fields.get(item), str) and fields[item].casefold() == "fanger"
            for item in comfort_fields
        ):
            empty_field = next(
                (field for field in comfort_fields if not fields.get(field)),
                None,
            )
            if empty_field is None:
                continue
            fields[empty_field] = "Fanger"
        schema.validate_instance_fields(object_type, fields)
        enabled += 1
    return enabled, people_zone_map


def _has_fanger_people(model: Mapping[str, Any]) -> bool:
    people = model.get("People")
    if not isinstance(people, Mapping):
        return False
    return any(
        isinstance(fields, Mapping)
        and any(
            isinstance(value, str)
            and field.startswith("thermal_comfort_model_")
            and value.casefold() == "fanger"
            for field, value in fields.items()
        )
        for fields in people.values()
    )


def _patch_period_and_timestep(
    model: dict[str, Any],
    schema: SchemaNavigator,
    period: PeriodProtocol,
    timestep_minutes: int,
) -> None:
    if 60 % timestep_minutes:
        raise EnergyPlusIntegrationError(
            f"Zone timestep {timestep_minutes} minutes does not divide one hour."
        )
    run_period_fields = {
        "begin_month": int(period.start_month),
        "begin_day_of_month": int(period.start_day),
        "end_month": int(period.end_month),
        "end_day_of_month": int(period.end_day),
    }
    schema.require_fields("RunPeriod", run_period_fields)
    run_periods = _instances(model, "RunPeriod")
    if not run_periods:
        run_periods["EcoLoop Run Period"] = {}
    selected_name = sorted(run_periods, key=str.casefold)[0]
    selected_fields = run_periods[selected_name]
    run_periods.clear()
    selected_fields.update(run_period_fields)
    run_periods["EcoLoop Evaluation Period"] = selected_fields

    timestep_type = "Timestep"
    schema.require_fields(timestep_type, ("number_of_timesteps_per_hour",))
    timesteps = _instances(model, timestep_type)
    if not timesteps:
        timesteps["EcoLoop Timestep"] = {}
    for fields in timesteps.values():
        fields["number_of_timesteps_per_hour"] = 60 // timestep_minutes


def patch_model(
    source_epjson: Mapping[str, Any],
    schema: SchemaNavigator,
    period: PeriodProtocol,
    timestep_minutes: int,
    *,
    controlled: bool,
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Return one prepared baseline or controlled epJSON model and metadata."""

    model = copy.deepcopy(dict(source_epjson))
    _patch_period_and_timestep(model, schema, period, timestep_minutes)
    (
        reference_heating,
        reference_cooling,
        actuated_heating,
        actuated_cooling,
        thermostat_count,
    ) = _install_baseline_schedules(model, schema, controlled=controlled)
    fanger_people, fanger_people_zone_map = _enable_fanger_when_supported(
        model,
        schema,
    )
    _add_outputs(
        model,
        schema,
        (reference_heating, reference_cooling),
        (actuated_heating, actuated_cooling),
        include_fanger=_has_fanger_people(model),
    )
    metadata = {
        "controlled": controlled,
        "reference_heating_schedule": reference_heating,
        "reference_cooling_schedule": reference_cooling,
        "actuated_heating_schedule": actuated_heating,
        "actuated_cooling_schedule": actuated_cooling,
        "thermostat_objects_patched": thermostat_count,
        "people_objects_fanger_enabled": fanger_people,
        "fanger_prerequisite_schedules": dict(_FANGER_SCHEDULE_VALUES),
        "fanger_people_zone_map": fanger_people_zone_map,
        "fanger_assumptions": {
            "work_efficiency": ("0.0 dimensionless external work for sedentary office activity"),
            "clothing_insulation": "0.5 clo summer office ensemble",
            "air_velocity": "0.1 m/s still-air office assumption",
            "mean_radiant_temperature": "EnclosureAveraged",
        },
    }
    return model, metadata


def _write_json(path: Path, payload: Mapping[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=True) + "\n",
        encoding="utf-8",
        newline="\n",
    )


def _sha256_model_text(path: Path) -> str:
    """Hash UTF-8 model text after canonicalizing every line ending to LF."""

    text = path.read_text(encoding="utf-8")
    canonical = text.replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _sha256_file(path: Path) -> str:
    """Hash an artifact exactly as written."""

    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _portable_repository_path(path: Path) -> str:
    """Return a portable repository path, or only a non-repository basename."""

    resolved = path.resolve()
    root = repository_root().resolve()
    try:
        return resolved.relative_to(root).as_posix()
    except ValueError:
        return resolved.name


def _portable_provenance_payload(
    provenance: ModelProvenance,
    repository_model: Path,
) -> dict[str, Any]:
    """Serialize model origin without embedding a developer-machine path."""

    root_license = repository_root() / "models" / "base" / "ENERGYPLUS_LICENSE.txt"
    license_name = (
        _portable_repository_path(root_license)
        if root_license.is_file()
        else provenance.license_path.name
        if provenance.license_path is not None
        else None
    )
    return {
        "repository_model": _portable_repository_path(repository_model),
        "repository_model_sha256": _sha256_model_text(repository_model),
        "repository_model_sha256_mode": "utf-8-text-lf-normalized",
        "source_name": provenance.source_name,
        "source_identity": provenance.source_path.name,
        "energyplus_version": provenance.energyplus_version,
        "energyplus_distribution": (
            f"EnergyPlus {provenance.energyplus_version}; installation is "
            "discovered locally at runtime"
        ),
        "license_path": license_name,
        "selection_reasons": list(provenance.selection_reasons),
    }


def _license_path(installation: EnergyPlusInstallation) -> Path | None:
    for name in ("LICENSE.txt", "LICENSE", "COPYING.txt", "Copyright.txt"):
        path = installation.home / name
        if path.is_file():
            return path.resolve()
    return None


def _copy_model_source(
    installation: EnergyPlusInstallation,
    source: Path,
    destination: Path,
) -> None:
    """Copy a normal IDF or officially expand an HVAC-template example."""

    text = source.read_text(encoding="utf-8", errors="replace").casefold()
    if "hvactemplate:" not in text:
        shutil.copy2(source, destination)
        return
    if installation.expand_objects is None or installation.idd is None:
        raise EnergyPlusIntegrationError(
            "The selected example contains HVACTemplate objects, but ExpandObjects "
            "or the version-matched Energy+.idd is unavailable."
        )
    with tempfile.TemporaryDirectory(prefix="ecoloop-expand-") as temporary:
        work = Path(temporary)
        shutil.copy2(source, work / "in.idf")
        shutil.copy2(installation.idd, work / "Energy+.idd")
        try:
            completed = subprocess.run(  # noqa: S603 - official fixed tool path
                [str(installation.expand_objects)],
                cwd=work,
                capture_output=True,
                check=False,
                text=True,
                timeout=120,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise EnergyPlusIntegrationError(
                f"ExpandObjects could not process {source}: {exc}"
            ) from exc
        expanded = work / "expanded.idf"
        if completed.returncode != 0 or not expanded.is_file():
            diagnostic = "\n".join(
                value.strip() for value in (completed.stdout, completed.stderr) if value.strip()
            )
            raise EnergyPlusIntegrationError(
                f"ExpandObjects failed for {source} (exit {completed.returncode}). "
                f"Output: {diagnostic or 'no diagnostic output'}"
            )
        shutil.copy2(expanded, destination)


def _copy_or_select_source(
    installation: EnergyPlusInstallation,
    configured_path: Path,
    source: Path | None,
) -> tuple[Path, ModelProvenance]:
    configured_path.parent.mkdir(parents=True, exist_ok=True)
    if source is not None:
        selected_path = source.expanduser().resolve()
        if not selected_path.is_file():
            raise EnergyPlusIntegrationError(
                f"Configured source model does not exist: {selected_path}"
            )
        reasons: tuple[str, ...] = ("explicit source model",)
    elif configured_path.is_file():
        selected_path = configured_path.resolve()
        reasons = ("existing version-controlled base model",)
    else:
        candidate = select_official_example(installation)
        selected_path = candidate.path
        reasons = candidate.reasons
    provenance = ModelProvenance(
        source_path=selected_path,
        source_name=selected_path.name,
        energyplus_version=installation.version or "unknown",
        energyplus_home=installation.home,
        license_path=_license_path(installation),
        selection_reasons=reasons,
    )
    if selected_path != configured_path.resolve():
        _copy_model_source(installation, selected_path, configured_path)
    return configured_path.resolve(), provenance


def _write_actuator_map(path: Path, metadata: Mapping[str, Any]) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=(
                "logical_action",
                "component_type",
                "control_type",
                "actuator_key",
                "reference_schedule",
                "required",
            ),
        )
        writer.writeheader()
        writer.writerow(
            {
                "logical_action": "heating_setpoint_c",
                "component_type": "Schedule:Compact",
                "control_type": "Schedule Value",
                "actuator_key": metadata["actuated_heating_schedule"],
                "reference_schedule": metadata["reference_heating_schedule"],
                "required": "true",
            }
        )
        writer.writerow(
            {
                "logical_action": "cooling_setpoint_c",
                "component_type": "Schedule:Compact",
                "control_type": "Schedule Value",
                "actuator_key": metadata["actuated_cooling_schedule"],
                "reference_schedule": metadata["reference_cooling_schedule"],
                "required": "true",
            }
        )


def _empty_action_schedule(path: Path) -> None:
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            (
                "simulation_timestamp",
                "observation_id",
                "action_generation",
                "heating_setpoint_c",
                "cooling_setpoint_c",
                "hold_minutes",
            )
        )


def prepare_models(
    settings: object,
    period: PeriodProtocol,
    source: Path | None = None,
    *,
    output_directory: Path | None = None,
) -> ModelArtifacts:
    """Prepare baseline, agent-ready, and replay-ready IDFs using EnergyPlus tooling.

    ``prepare-model`` uses the canonical repository directory. Runtime callers
    pass a run-local directory so an experiment cannot mutate tracked models.
    """

    installation = require_energyplus(settings, model_tooling=True)
    if installation.schema is None:
        raise EnergyPlusIntegrationError("EnergyPlus schema is required for model preparation.")
    root = repository_root()
    configured_model_method = getattr(settings, "resolved_model_path", None)
    configured_model = (
        configured_model_method()
        if callable(configured_model_method)
        else root / "models" / "base" / "building.idf"
    )
    source_model, provenance = _copy_or_select_source(
        installation,
        Path(configured_model),
        source,
    )
    generated = (
        output_directory.expanduser().resolve()
        if output_directory is not None
        else (root / "models" / "generated").resolve()
    )
    generated.mkdir(parents=True, exist_ok=True)
    schema_data, schema = load_epjson_schema(installation.schema)
    del schema_data

    with tempfile.TemporaryDirectory(prefix="ecoloop-prepare-") as temporary:
        work = Path(temporary)
        source_epjson_path = work / "source.epJSON"
        convert_input_format(installation, source_model, "epJSON", source_epjson_path)
        try:
            source_epjson = json.loads(source_epjson_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise EnergyPlusIntegrationError(
                f"Converted epJSON could not be loaded: {source_epjson_path}: {exc}"
            ) from exc
        if not isinstance(source_epjson, dict):
            raise EnergyPlusIntegrationError("Converted model is not an epJSON object.")

        timestep_minutes = int(getattr(settings, "zone_timestep_minutes", 15))
        baseline_epjson, baseline_metadata = patch_model(
            source_epjson,
            schema,
            period,
            timestep_minutes,
            controlled=False,
        )
        agent_epjson, agent_metadata = patch_model(
            source_epjson,
            schema,
            period,
            timestep_minutes,
            controlled=True,
        )
        baseline_json_path = work / "baseline.epJSON"
        agent_json_path = work / "agent_ready.epJSON"
        _write_json(baseline_json_path, baseline_epjson)
        _write_json(agent_json_path, agent_epjson)
        baseline_idf = generated / "baseline.idf"
        agent_idf = generated / "agent_ready.idf"
        replay_idf = generated / "agent_replay.idf"
        convert_input_format(installation, baseline_json_path, "idf", baseline_idf)
        convert_input_format(installation, agent_json_path, "idf", agent_idf)
        # Replay uses the same verified actuator-capable model. The replay runtime
        # applies the exported schedule without invoking the model host.
        shutil.copy2(agent_idf, replay_idf)

    action_schedule = generated / "action_schedule.csv"
    _empty_action_schedule(action_schedule)
    actuator_map = generated / "actuator_map.csv"
    _write_actuator_map(actuator_map, agent_metadata)
    provenance_path = source_model.parent / "PROVENANCE.json"
    _write_json(
        provenance_path,
        _portable_provenance_payload(provenance, source_model),
    )
    manifest = generated / "preparation-manifest.json"
    _write_json(
        manifest,
        {
            "energyplus_version": installation.version,
            "energyplus_distribution": (
                f"EnergyPlus {installation.version}; installation is discovered locally at runtime"
            ),
            "source_model": _portable_repository_path(source_model),
            "source_model_sha256": _sha256_model_text(source_model),
            "source_model_sha256_mode": "utf-8-text-lf-normalized",
            "period": {
                "start_month": int(period.start_month),
                "start_day": int(period.start_day),
                "end_month": int(period.end_month),
                "end_day": int(period.end_day),
            },
            "baseline": baseline_metadata,
            "agent_ready": agent_metadata,
            "generated_artifacts": {
                "baseline_idf_sha256": _sha256_file(baseline_idf),
                "agent_ready_idf_sha256": _sha256_file(agent_idf),
                "agent_replay_idf_sha256": _sha256_file(replay_idf),
                "actuator_map_sha256": _sha256_file(actuator_map),
            },
            "replay_method": (
                "EnergyPlus Runtime API applies action_schedule.csv to the same discovered "
                "schedule actuators; no local model inference is called."
            ),
            "runtime_electricity_signals": {
                "preferred": "Electricity:Facility",
                "fallback": "ElectricityNet:Facility",
                "note": (
                    "The Runtime API records which handle supplied callback telemetry. "
                    "Official final energy always comes from Electricity:Facility in "
                    "EnergyPlus SQL/CSV and is cross-checked."
                ),
            },
            "timestep_minutes": int(getattr(settings, "zone_timestep_minutes", 15)),
        },
    )
    return ModelArtifacts(
        source_model=source_model,
        baseline_model=baseline_idf,
        agent_ready_model=agent_idf,
        agent_replay_model=replay_idf,
        action_schedule=action_schedule,
        actuator_map=actuator_map,
        provenance=provenance_path,
        preparation_manifest=manifest,
    )


@dataclass(frozen=True, slots=True)
class ReplayAction:
    """One validated applied action exported for deterministic replay."""

    simulation_timestamp: str
    observation_id: int
    action_generation: int
    heating_setpoint_c: float
    cooling_setpoint_c: float
    hold_minutes: int

    def __post_init__(self) -> None:
        for name, value in (
            ("heating_setpoint_c", self.heating_setpoint_c),
            ("cooling_setpoint_c", self.cooling_setpoint_c),
        ):
            if not math.isfinite(value):
                raise ValueError(f"{name} must be finite")
        if self.heating_setpoint_c >= self.cooling_setpoint_c:
            raise ValueError("Replay heating setpoint must be below cooling setpoint")
        if self.observation_id < 1 or self.action_generation < 1 or self.hold_minutes < 1:
            raise ValueError("Replay identifiers and hold duration must be positive")


def write_action_schedule(actions: Iterable[ReplayAction], path: Path) -> Path:
    """Write validated applied actions in deterministic generation order."""

    ordered = sorted(
        actions,
        key=lambda item: (
            item.simulation_timestamp,
            item.action_generation,
            item.observation_id,
        ),
    )
    seen_generations: set[int] = set()
    last_generation = 0
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(
            (
                "simulation_timestamp",
                "observation_id",
                "action_generation",
                "heating_setpoint_c",
                "cooling_setpoint_c",
                "hold_minutes",
            )
        )
        for action in ordered:
            if (
                action.action_generation in seen_generations
                or action.action_generation <= last_generation
            ):
                raise EnergyPlusIntegrationError(
                    f"Replay action generation is duplicate or non-monotonic: "
                    f"{action.action_generation}."
                )
            seen_generations.add(action.action_generation)
            last_generation = action.action_generation
            writer.writerow(
                (
                    action.simulation_timestamp,
                    action.observation_id,
                    action.action_generation,
                    format(action.heating_setpoint_c, ".6f"),
                    format(action.cooling_setpoint_c, ".6f"),
                    action.hold_minutes,
                )
            )
    return path
